# -*- coding: utf-8 -*-
"""22101156-2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z2-8a9HrIcMxIPHXWVpOtC41OWx6FgC1
"""

import sys

request_seq = [98, 183, 37, 122, 14, 124, 65, 67]
head = 53
total_movement = 0
visited = [head]
print("Request sequence:", request_seq)
while len(visited) <= len(request_seq):
    min_diff = sys.maxsize
    index = -1
    for j in range(len(request_seq)):
        if request_seq[j] not in visited:
            diff = abs(head - request_seq[j])
            if diff < min_diff:
                min_diff = diff
                index = j
    head = request_seq[index]
    visited.append(request_seq[index])
    total_movement += min_diff

print("Total head movement:", total_movement)