# -*- coding: utf-8 -*-
"""22101156-1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NkB1NQ4N8WGJU2KCeFudQGj5ojatYaVR
"""

def sjf_non_preemptive(pro):
    n = len(pro)
    time = 0
    completed = [False] * n
    scheduled = []
    completed_count = 0
    while completed_count < n:
        idx = -1
        min_burst = float('inf')
        for i in range(n):
            if not completed[i] and pro[i]['arrival'] <= time and pro[i]['burst'] < min_burst:
                min_burst = pro[i]['burst']
                idx = i

        if idx == -1:
            time += 1
            continue
        pro[idx]['comp_time'] = time + pro[idx]['burst']
        pro[idx]['ta_time'] = pro[idx]['comp_time'] - pro[idx]['arrival']
        pro[idx]['waiting_time'] = pro[idx]['ta_time'] - pro[idx]['burst']

        time = pro[idx]['comp_time']
        completed[idx] = True
        completed_count += 1
        scheduled.append(pro[idx])
    print("Using Non-Preemptive SJF")
    print("PID\tAT\tBT\tCT\tTAT\tWT")
    total_tat = 0
    total_wt = 0
    for p in scheduled:
        print(f"{p['pid']}\t{p['arrival']}\t{p['burst']}\t{p['comp_time']}\t{p['ta_time']}\t{p['waiting_time']}")
        total_tat += p['ta_time']
        total_wt += p['waiting_time']
    print("Average Turnaround Time:", total_tat / n)
    print("Average Waiting Time:", total_wt / n)
processes = [
    {'pid': 'P1', 'arrival': 0, 'burst': 6},
    {'pid': 'P2', 'arrival': 1, 'burst': 8},
    {'pid': 'P3', 'arrival': 2, 'burst': 7},
    {'pid': 'P4', 'arrival': 3, 'burst': 3},
]

sjf_non_preemptive(processes)