# -*- coding: utf-8 -*-
"""CSE(406)-lab5(1)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EEsyHRkDKutOqza76PhbCW1ouVyUurcN
"""

size = 5;
def FCFS(arr, head):
    seek_count = 0;
    distance, cur_seq = 0, 0;
    for i in range(size):
        cur_seq = arr[i];
        distance = abs(cur_seq - head);
        seek_count += distance;
        head = cur_seq;

    print("Total seek operations = ",seek_count);
    print("Seek Sequence is");

    for i in range(size):
        print(arr[i]);

arr = [ 176, 39, 114, 90, 26 ];
head = 60;
FCFS(arr, head);