# -*- coding: utf-8 -*-
"""CSE406-lab2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10TLF72G2pV5BLEl8YhRnRd_qzNVOSyrh
"""

processes = [1, 2, 3, 4, 5]
at_time = [0, 1, 2, 3, 0]
bt_time = [3, 2, 1, 4, 2]
n = len(processes)

ct_time = [0] * n
tat_time = [0] * n
wat_time = [0] * n
completed = [False] * n

current_time = 0
completed_processes = 0

print("Pid\tat\tbt\tct\ttat\twt")

while completed_processes < n:
    idx = -1
    min_bt = float('inf')
    for i in range(n):
        if at_time[i] <= current_time and not completed[i]:
            if bt_time[i] < min_bt:
                min_bt = bt_time[i]
                idx = i
            elif bt_time[i] == min_bt:
                if at_time[i] < at_time[idx]:
                    idx = i

    if idx != -1:
        current_time += bt_time[idx]
        ct_time[idx] = current_time
        tat_time[idx] = ct_time[idx] - at_time[idx]
        wat_time[idx] = tat_time[idx] - bt_time[idx]
        completed[idx] = True
        completed_processes += 1
    else:
        current_time += 1

for i in range(n):
    print(f"P{processes[i]}\t{at_time[i]}\t{bt_time[i]}\t{ct_time[i]}\t{tat_time[i]}\t{wat_time[i]}")

avg_wt = sum(wat_time) / n
avg_tat = sum(tat_time) / n
print(f"\nAverage Waiting Time = {avg_wt:.2f}")
print(f"Average Turnaround Time = {avg_tat:.2f}")