# -*- coding: utf-8 -*-
"""CSE406-Lab1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XPFC8zAnbvH4JwhKU62zpL42e7A1Hpxl
"""

processes = [1, 2, 3, 4]
at_time = [0, 1, 2, 3]
bt_time = [3, 2, 1, 4]
n = len(processes)

ct_time = [0] * n
tat_time = [0] * n
wat_time = [0] * n
for i in range(n):
  for j in range(i + 1, n):
               if at_time[i] > at_time[j]:
                  at_time[i], at_time[j] = at_time[j], at_time[i]
                  bt_time[i], bt_time[j] = bt_time[j], bt_time[i]
                  processes[i], processes[j] = processes[j], processes[i]

for i in range(n):
    if i == 0:
        ct_time[i] = at_time[i] + bt_time[i]
    else:
        if at_time[i] > ct_time[i - 1]:
            ct_time[i] = at_time[i] + bt_time[i]
        else:
            ct_time[i] = ct_time[i - 1] + bt_time[i]

    tat_time[i] = ct_time[i] - at_time[i]
    wat_time[i] = tat_time[i] - bt_time[i]
print("Pid\tat\tbt\tct\ttat\twt")
for i in range(n):
    print(f"P{processes[i]}\t{at_time[i]}\t{bt_time[i]}\t{ct_time[i]}\t{tat_time[i]}\t{wat_time[i]}")
avg_wt = sum(wat_time) / n
avg_tat = sum(tat_time) / n
print(f"\nAverage Waiting Time = {avg_wt:.2f}")
print(f"Average Turnaround Time = {avg_tat:.2f}")