# -*- coding: utf-8 -*-
"""lab-4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ktZz4pDSOOY9kp6o110R8N2SQvqgIILn
"""

processes = [
    ["P1", 0, 11, 2],
    ["P2", 5, 28, 0],
    ["P3", 12, 2, 3],
    ["P4", 2, 10, 1],
    ["P5", 9, 16, 4]
]
n = len(processes)
for p in processes:
    p.extend([0, 0, 0, False])
time = 0
completed = 0
while completed < n:
    idx = -1
    highest_priority = float('inf')
    for i in range(n):
        if processes[i][1] <= time and not processes[i][7]:
            if processes[i][3] < highest_priority:
                highest_priority = processes[i][3]
                idx = i
    if idx != -1:
        current = processes[idx]
        time += current[2]
        current[4] = time
        current[5] = current[4] - current[1]
        current[6] = current[5] - current[2]
        current[7] = True
        completed += 1
    else:
        time += 1
print(f"{'PID':<5} {'AT':<5} {'BT':<5} {'Priority':<10} {'CT':<5} {'TAT':<5} {'WT':<5}")
total_tat = 0
total_wt = 0

for p in processes:
    total_tat += p[5]
    total_wt += p[6]
    print(f"{p[0]:<5} {p[1]:<5} {p[2]:<5} {p[3]:<10} {p[4]:<5} {p[5]:<5} {p[6]:<5}")

print(f"\nAverage Turnaround Time: {total_tat / n:.2f}")
print(f"Average Waiting Time   : {total_wt / n:.2f}")