# -*- coding: utf-8 -*-
"""Lab-6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BjIkulOy1QEiggKT7D2Q9QEBhL2ZFex4
"""

import sys
req_seq=[176,39,49,114,90,26]
req_seq.sort()
head=39
diff=0
x=0
ind=0
sum=0
print(req_seq)
visited=[]
visited.append(head)
while(len(visited)<len(req_seq)):
    check=sys.maxsize
    for j in range(len(req_seq)):
        found=False
        for x in range(len(visited)):
            if visited[x]==req_seq[j]:
                found=True
                break
        if found==True:
            continue
        diff=abs(head-req_seq[j])
        if diff<check:
            check=diff
            ind=j
    head=req_seq[ind]
    visited.append(req_seq[ind])
    sum+=check
print(sum)